name: Metrics
on:
  # Roda 1x por dia à meia-noite
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente
  workflow_dispatch:
  # Roda quando der push na main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Configurações Visuais
          user: giovanicenta
          template: classic
          config_timezone: America/Sao_Paulo
          
          # O SEGREDO ESTÁ AQUI: 
          # Removemos 'activity' (zeros) e 'community'. 
          # Deixamos 'header' (seu perfil) e 'repositories' (suas 35 estrelas)
          base: header, repositories, metadata
          
          # Plugin de Linguagens (Isso é ótimo para Data Science)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 4
          
          # DICA EXTRA: Adicionei linhas de código. 
          # Para Data Science costuma dar números altos e impressionantes.
          plugin_lines: yes
